#!/bin/bash

set -x

# This script is a modified copy from https://github.com/cosmos/relayer/blob/14195ec4c8c19f86a3b6bbe3750f392e436a5879/scripts/two-chainz

CURDIR=$(cd $(dirname "$0"); pwd)

CHAIN_DATA="${CURDIR}/../data"
RELAYER_CONF="$HOME/.urelayer"

# Ensure ${TM_BINARY} is installed
if ! [ -x ${TM_BINARY} ]; then
  echo "Error: ${TM_BINARY} is not installed." >&2
  exit 1
fi

# Ensure ${RLY_BINARY} is installed
if ! [ -x ${RLY_BINARY} ]; then
  echo "Error: ${RLY_BINARY} is not installed." >&2
  exit 1
fi

# Display software version for testers
echo "GAIA VERSION INFO:"
${TM_BINARY} version --long

# Ensure jq is installed
if [[ ! -x "$(which jq)" ]]; then
  echo "jq (a tool for parsing json in the command line) is required..."
  echo "https://stedolan.github.io/jq/download/"
  exit 1
fi

# Ensure user understands what will be deleted
if [[ -d $CHAIN_DATA ]] && [[ ! "$1" == "skip" ]]; then
  read -p "$(basename $0) will delete \"$CHAIN_DATA\" and \"$RELAYER_CONF\" folders. Do you wish to continue? (y/n): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      exit 1
  fi
fi

# Delete data from old runs
rm -rf $CHAIN_DATA &> /dev/null
rm -rf $RELAYER_CONF &> /dev/null

# Stop existing ${TM_BINARY} processes
# killall ${TM_BINARY} &> /dev/null #=> got 'No matching processes belonging to you were found'
killall simd &> /dev/null

set -e

chainid0=ibc0

echo "Generating gaia configurations..."
mkdir -p $CHAIN_DATA # && cd $CHAIN_DATA && cd ../
${CURDIR}/one-chain ${TM_BINARY} $chainid0 ./data 26657 26656 6060 9090

[ -f $CHAIN_DATA/$chainid0.log ] && echo "$chainid0 initialized. Watch file $CHAIN_DATA/$chainid0.log to see its execution."
