#!/bin/bash

set -x

# configures fabric chain and the relayer for now.

# Ensure ${RLY_BINARY} is installed
if ! [ -x ${RLY_BINARY} ]; then
  echo "Error: ${RLY_BINARY} is not installed." >&2
  exit 1
fi

CURDIR=$(cd $(dirname "$0"); pwd)

RELAYER_CONF="$HOME/.urelayer"
RLY="${RLY_BINARY} --debug"
FIXTURES_DIR=${CURDIR}/../fixtures

# Setup fixtures for fabric chain
${CURDIR}/prepare-fixtures

echo "Generating ${RLY_BINARY} configurations..."

${RLY} config init
${RLY} chains add-dir ${CURDIR}/../configs/relayer/

# setup key for tendermint client
SEED0=$(jq -r '.mnemonic' $TM_DATA_DIR/ibc0/relayer_seed.json)
echo "Key $(${RLY} tendermint keys restore ibc0 testkey "$SEED0") imported from ibc0 to relayer..."

# setup wallet for fabric client
${RLY} fabric wallet populate ibc1 --cert ${FIXTURES_DIR}/certs/platformer-user-signcert.pem --key ${FIXTURES_DIR}/keys/clients/platformer-user-priv_sk
# initialize the state of chaincode
${RLY} fabric chaincode init ibc1
