#!/bin/bash

set -x

# two-chainz creates two chains (fabric and tendermint) and configures the relayer to

CURDIR=$(cd $(dirname "$0"); pwd)

DATA_DIR="${CURDIR}/../data"
RELAYER_CONF="$HOME/.urelayer"
RLY="${RLY_BINARY} --debug"
FIXTURES_DIR=${CURDIR}/../fixtures

# Ensure ${TM_BINARY} is installed
if ! [ -x ${TM_BINARY} ]; then
  echo "Error: ${TM_BINARY} is not installed." >&2
  exit 1
fi

# Ensure ${RLY_BINARY} is installed
if ! [ -x ${RLY_BINARY} ]; then
  echo "Error: ${RLY_BINARY} is not installed." >&2
  exit 1
fi

# Run tendermint chain
${CURDIR}/tm-chain
# Run fabric chain
${CURDIR}/fab-chain

echo "Generating ${RLY_BINARY} configurations..."

${RLY} config init
${RLY} chains add-dir ${CURDIR}/../configs/relayer/

# setup key for tendermint client
SEED0=$(jq -r '.mnemonic' $DATA_DIR/ibc0/relayer_seed.json)
echo "Key $(${RLY} tendermint keys restore ibc0 testkey "$SEED0") imported from ibc0 to relayer..."

# setup wallet for fabric client
${RLY} fabric wallet populate ibc1 --cert ${FIXTURES_DIR}/certs/platformer-user-signcert.pem --key ${FIXTURES_DIR}/keys/clients/platformer-user-priv_sk
# initialize the state of chaincode
${RLY} fabric chaincode init ibc1
